server:
  port: 8080

spring:
  mail:
    host: smtp.qq.com  # 只发送不接收
    username: 204126329@qq.com  # 自己的QQ
    password: xgmpoyvzeoqabhdc  # 提供的密码  不是自己的登录密码
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  #  resources:
#    static-locations: [classpath:/backend/,/front/]  #  这里配置文件改变静态资源映射 没有生效感觉
#    static-locations: [classpath:/static/]  #  这里配置文件改变静态资源映射 没有生效感觉
  application:
    name: reggie_take_out
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.143.25.143:3306/reggie?characterEncoding=utf-8
        username: root
        password: kang
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.143.25.143/reggie?characterEncoding=utf-8
        username: root
        password: kang
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询  还有其他的从机mysql服务器
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
      username: root
      password: 123456
  cache:
    redis:
      time-to-live: 18000000 # 设置超时时间
  redis:
    host: 43.143.25.143
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        min-idle: 0
        max-wait: 1
        max-idle: 5
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # sql日志开启
  global-config:
    db-config:
      id-type: ASSIGN_ID  # 雪花算法
reggie:
#  path: src/main/resources/static/
#  path: C:\Users\20412\Desktop\learningroom\reggie-gzj-test\src\main\resources\static\
  path: /usr/local/img
#  path: D:\
#Redis服务器地址
#  spring.redis.host=192.168.140.136
#
#  #Redis服务器连接端口
#  spring.redis.port=6379
#  #Redis数据库索引（默认为0）
#  spring.redis.database= 0
#  #连接超时时间（毫秒）
#  spring.redis.timeout=1800000
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.lettuce.pool.max-active=20
#  #最大阻塞等待时间(负数表示没限制)
#  spring.redis.lettuce.pool.max-wait=-1
#  #连接池中的最大空闲连接
#  spring.redis.lettuce.pool.max-idle=5
#  #连接池中的最小空闲连接
#  spring.redis.lettuce.pool.min-idle=0
